<a href="https://colab.research.google.com/github/stakah/mycolab/blob/main/DSA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DSA


## Lists


Simple list initialization.

In [1]:
list_a = ["John", 33, "Toronto", True]
print(list_a)

['John', 33, 'Toronto', True]


Accessing element by index.

In [2]:
bin_colors = ["Red", "Green", "Blue", "Yellow"]
bin_colors[1]

'Green'

Accessing elements by range.

In [3]:
bin_colors[0:2]

['Red', 'Green']

In [4]:
bin_colors[2:]

['Blue', 'Yellow']

In [5]:
bin_colors[:2]

['Red', 'Green']

Accessing elements by negative indexes.

In [6]:
bin_colors[:-1]

['Red', 'Green', 'Blue']

In [7]:
bin_colors[-2:-1]

['Blue']

Nesting.

In [8]:
a = [1, 2, [100, 200, 300], 6]
max(a[2])

300

In [9]:
a[2][1]

200

Iteration.

In [10]:
for color_a in bin_colors:
  print(color_a + " Square")

Red Square
Green Square
Blue Square
Yellow Square


Adding element.

In [11]:
bin_colors.append('Purple')
print(bin_colors)

['Red', 'Green', 'Blue', 'Yellow', 'Purple']


Removing element.

In [12]:
some_color = bin_colors.pop()
print(some_color)
print(bin_colors)

Purple
['Red', 'Green', 'Blue', 'Yellow']


The range() function

In [13]:
x = range(4)
for n in x:
  print(n)

0
1
2
3


In [14]:
odd_num = range(1, 30, 2)
for n in odd_num:
  print(n)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29


In [15]:
import random
dice_output = [ random.randint(1, 6) for x in range(10)]
print(dice_output)

[2, 1, 3, 4, 6, 2, 1, 4, 3, 6]


### Time complexity

| Action               | Complexity |
|----------------------|------------|
| Inserting an element | O(1)       |
| Deleting an element  | O(n)       |
| Slicing              | O(n)       |
| Finding an element   | O(n)       |
| Copying              | O(n)       |

## Tuples

In [17]:
box_colors = ("Red", "Green", "Blue", "Yellow")
print(f"The second element of the tuple is \"{bin_colors[1]}\"")

The second element of the tuple is "Green"


In [18]:
print(f"The elements after third element onwards are {box_colors[2:]}")

The elements after third element onwards are ('Blue', 'Yellow')


In [19]:
nested_tuple = (1, 2, (100, 200, 300), 6)
print(f"The maximum value of the inner tuple is {max(nested_tuple[2])}")

The maximum value of the inner tuple is 300


### Time Complexity

| Action               | Complexity |
|----------------------|------------|
| Accessing an element | O(1)       |
| Slicing              | O(n)       |
| Element retrieval    | O(n)       |
| Copying              | O(n)       |

## Dictionaries

In [20]:
color_codes = {
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}
print(color_codes)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [21]:
color_codes.get("approved_color")

'Green'

In [22]:
color_codes["manual_color"]

'Yellow'

In [23]:
color_codes["special_color"] = "Purple"
print(color_codes)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red', 'special_color': 'Purple'}


In [24]:
for k,v in color_codes.items():
  print(f"{k}\t-> {v} color")

manual_color	-> Yellow color
approved_color	-> Green color
refused_color	-> Red color
special_color	-> Purple color


In [25]:
del color_codes["refused_color"]
print(color_codes)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'special_color': 'Purple'}


### Time Complexity

| Action                      | Complexity |
|-----------------------------|------------|
| Accessing a value by key    | O(1)       |
| Inserting an key-value pair | O(1)       |
| Deleting a key-value pair   | O(1)       |
| Searching for a key         | O(1)       |
| Copying                     | O(n)       |

## Sets

In [26]:
green_leaves = {"green", "leaves"}
print(green_leaves)

{'leaves', 'green'}


In [27]:
green_leaves = {"leaves", "green", "leaves"}
print(green_leaves)

{'leaves', 'green'}


In [28]:
yellow = {"dandelions", "fire hydrant", "leaves"}
red = {"fire hydrant", "blood", "rose", "leaves"}
print(f"The union of yellow and red sets is {yellow | red}")
print(f"The intersection of yellow and red sets is {yellow & red}")

The union of yellow and red sets is {'blood', 'rose', 'dandelions', 'leaves', 'fire hydrant'}
The intersection of yellow and red sets is {'fire hydrant', 'leaves'}


In [29]:
for x in yellow:
  print(x)

dandelions
fire hydrant
leaves


In [32]:
print(f'There are "leaves" in the yellow set? {"leaves" in yellow}')

There are "leaves" in the yellow set? True


### Time Complexity

| Action            | Complexity |
|-------------------|------------|
| Add an element    | O(1)       |
| Remove an element | O(1)       |
| Copying           | O(n)       |

## Series and DataFrames

## Series

In [33]:
import pandas as pd
person_1 = pd.Series(["John", "Male", 33, True])
print(person_1)

0    John
1    Male
2      33
3    True
dtype: object


## DataFrame

In [34]:
employees_df = pd.DataFrame([
    ["1", "Fares", 32, True],
    ["2", "Elena", 23, False],
    ["3", "Doug", 40, True]
])
employees_df.columns = ["id", "name", "age", "decision"]
print(employees_df)

  id   name  age  decision
0  1  Fares   32      True
1  2  Elena   23     False
2  3   Doug   40      True


### Creating a subset of DataFrame

* Column selection
* Row selection

#### Column Selection

In [35]:
employees_df[["name", "age"]]

name  age
0  Fares   32
1  Elena   23
2   Doug   40

In [36]:
employees_df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

#### Row Selection

* By specifying their position
* By specifying a filter

In [37]:
employees_df.iloc[1:3,:]

id   name  age  decision
1  2  Elena   23     False
2  3   Doug   40      True

In [38]:
employees_df[employees_df.age > 30]

id   name  age  decision
0  1  Fares   32      True
2  3   Doug   40      True

In [39]:
employees_df[(employees_df.age < 35) & (employees_df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

### Time Complexity

<table>
<thead>
<tr>
<th>Operation</th><th>Complexithy</th>
</tr>
</thead>
<tbody>
<tr>
<th colspan=2>Selection operations</th>
</tr>
<tr>
<th>Column selection<br>
Accessing a DataFrame column by [] or .
</th><td>O(1)</td>
</tr>
<tr>
<th>Row selection<br>
Using methods like .loc[] or .iloc[]
</th>
<td>O(n)</td>
</tr>

<tr>
<th colspan=2>Insertion operations</th>
</tr>
<tr>
<th>Column insertion<br>

</th><td>O(1)</td>
</tr>
<tr>
<th>Row insertion<br>
Adding rows using methods like .append() or .concat()
</th>
<td>O(n)</td>
</tr>

<tr>
<th colspan=2>Deletion operations</th>
</tr>
<tr>
<th>Column deletion<br>
Using .drop() method
</th><td>O(1)</td>
</tr>
<tr>
<th>Row deletion<br>
Similar to row insertion
</th>
<td>O(n)</td>
</tr>
</tbody>
</table>

## Matrices

In [41]:
import numpy as np
matrix_1 = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])
print(matrix_1)
print(type(matrix_1))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>


### Time Complexity

| Action                | Complexity |
|-----------------------|------------|
|Access                 | O(1)       |
| Appending             | O(1) (average), O(n) (worst case) |
| Matrix multiplication | O(n^3) (worst case) |